# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12cGl2uVtEMixSy9cmZ1NR9r3FKnPVB-M
"""

import numpy as np

b=np.arange(100,200,5)
array=b[0:16].reshape(8,2)

print(array)

